location_app/app/__init__.py
from flask import Flask
from app import mqtt, routes


def make_app():
    """
    Makes the app object with the configuration from
    an environment variable and connects routes and mqtt
    to the app
    """
    app = Flask(__name__)
    app.config.from_envvar('MYAPP_SETTINGS')

    mqtt.init_app(app)

    routes.init_app(app)
    return app

location_app/app/mqtt/__init__.py
from flask_mqtt import Mqtt
from app.mqtt import mqtt_message_handler


def init_app(app):
    """
    Function to connect the mqtt to the app and setup
    on connect and on message callbacks
    """
    mqtt = Mqtt(app)

    @mqtt.on_connect()
    def handle_connect(client, userdata, flags, rc):
        mqtt.subscribe('owntracks/4009user/#')

    @mqtt.on_message()
    def handle_mqtt_message(client, userdata, msg):
        mqtt_message_handler.getMsg(msg)

location_app/app/routes/__init__.py
# Imports all blueprints so that they can be
# connected to the app object

from .index import index_bl
from .main import main_bl
from .map import map_bl
from .login import login_bl
from .profile import prof_bl
from .average import average_bl


def init_app(app):
    """
    Registers all blueprints to the app with
    the appropriate url prefix
    """
    app.register_blueprint(index_bl)
    app.register_blueprint(main_bl, url_prefix="/main")
    app.register_blueprint(map_bl, url_prefix="/map")
    app.register_blueprint(login_bl, url_prefix="/login")
    app.register_blueprint(prof_bl, url_prefix="/profile")
    app.register_blueprint(average_bl, url_prefix="/average")

location_app/app/routes/account.py
from flask import Blueprint, render_template, request, url_for, escape, redirect, session
from app.functions.data_tools import data_getter

acc_bl = Blueprint('acc', __name__)

@acc_bl.route("/", methods = ["GET", "POST"])
def index():
    return render_template("account_index.html")

location_app/app/routes/average.py
from flask import (Blueprint, render_template, request,
                   url_for, escape, redirect, session)
from app.functions.data_tools import data_getter


average_bl = Blueprint('average', __name__)

@average_bl.route("/", methods = ["GET"])
def index():
    """
    Renders the average index page with locations from the user
    """
    _locations = data_getter.get_locations_for(session['username'])
    return render_template("average/index.html", 
                           locations = _locations)

location_app/app/routes/index.py
from flask import Blueprint, url_for, redirect, session


index_bl = Blueprint('index', __name__) 

@index_bl.route("/", methods = ["GET", "POST"])
def index():
    """
    If there is user data saved in cookies it goes to
    the main page otherwise it will go to the login page
    """
    user = session.get('username')
    session['advanced'] = 0
    if user:
        return redirect(url_for('main.index'))
    else:
        return redirect(url_for('login.index'))

location_app/app/routes/login.py
from flask import (Blueprint, render_template, request,
                   url_for, redirect, session)
from app.functions.auth.login import login
from app.functions.auth.create_profile import create_profile
from app.functions.auth.change_password import change_password
from app.functions.data_tools.data_getter import get_dates

login_bl = Blueprint('login', __name__)

@login_bl.route("/", methods = ["GET", "POST"])
def index():
    """
    Renders the login page, handles POST requests for logging in
    and displays errors on the page also takes the user to the
    main page after successful login
    """
    if request.method == "POST":
        _status = login(request.form)
        if _status == "success":
            session["username"] = request.form["username"]
            return redirect(url_for('main.index'))
        else:
            return render_template("login/index.html",
                                   status = _status)
    return render_template("login/index.html",
                           status = "0")


@login_bl.route("/create_account", methods = ["GET", "POST"])
def create_account():
    """
    Renders the login page, handles POST requests for creating
    an account and displays errors on the page also takes the user
    back to the login page after creating the account
    """
    if request.method == "POST":
        _status = create_profile(request.form)
        if _status == "success":
            return redirect(url_for('login.index'))
        else:
            return render_template("login/create.html",
                                   status = _status,
                                   time = get_dates())
    return render_template("login/create.html", 
                           status = "0",
                           time = get_dates())


@login_bl.route("/forgot_password", methods = ["GET", "POST"])
def forgot_password():
    """
    Renders the login page, handles POST requests 
    and displays errors on the page also takes the user back to 
    the login page after changing the password 
    """
    if request.method == "POST":
        _status = change_password(request.form)
        if _status == "success":
            return redirect(url_for('login.index'))
        else:
            return render_template("login/forgot.html", 
                                   status = _status,
                                   time = get_dates())
    return render_template("login/forgot.html",
                           status = "0",
                           time = get_dates())

location_app/app/routes/main.py
from flask import (Blueprint, render_template,
                   url_for, redirect, session)
from app.functions.data_tools import data_getter


main_bl = Blueprint('main', __name__)

@main_bl.route("/")
def index():
    """
    Renders the main page with users locations and preffered view
    """
    _locations = data_getter.get_locations_for(session['username'])
    return render_template("main/index.html", 
                           locations = _locations,
                           advanced = session['advanced'])

@main_bl.route("/advanced")
def advanced():
    """
    Changes the preffered view and saves it in cookies
    """
    if session['advanced'] == 0:
        session['advanced'] = 1
    else:
        session['advanced'] = 0
    return redirect(url_for('main.index'))

@main_bl.route("/logout")
def logout():
    """
    Deletes users data from cookies and goes to the login page
    """
    session['username'] = ""
    return redirect(url_for('index.index'))

location_app/app/routes/map.py
from flask import Blueprint, render_template, session
from app.functions.data_tools import data_getter


map_bl = Blueprint('map', __name__)

@map_bl.route("/", methods = ["GET", "POST"])
def index():
    """
    Renders the map page with all the data 
    thats needed for calculations
    """
    _locations = data_getter.get_map_locations_for(session['username'])
    _dates = data_getter.get_map_location_dates(session['username'])
    _weight = data_getter.get_weight_for(session['username'])
    _color = data_getter.get_color_for(session['username'])
    return render_template("map/index.html", 
                           locations = _locations,
                           dates = _dates,
                           weight = _weight,
                           color = _color)

location_app/app/routes/profile.py
from flask import (Blueprint, render_template, request,
                   url_for, redirect, session)
from app.functions.data_tools import data_getter

prof_bl = Blueprint('prof', __name__)

@prof_bl.route("/", methods = ["GET", "POST"])
def index():
    """
    Renders the profile page with user data and handles
    changing of the weight and color through POST method
    """
    if request.method == "POST":
        data = request.form
        data_getter.update_data_for(session['username'], data)
    _user = data_getter.get_user_for(session['username'])
    _locations = data_getter.get_map_locations_for(session['username'])
    _dates = data_getter.get_map_location_dates(session['username'])
    return render_template("profile/index.html",
                           user = _user,
                           locations = _locations,
                           dates = _dates)


    

location_app/app/templates/average/index.html
{% extends 'base_page.html' %}

<!-- TITLE -->
{% block title %} Average {% endblock %} 

<!-- JS -->
{% block js %}

<script type="text/javascript" src="{{ url_for('static', filename='js/average/index.js') }}"></script> 
<script type="text/javascript" src="{{ url_for('static', filename='js/math.js') }}"></script> 

{% endblock %}

<!-- CSS -->
{% block css %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/average/index.css') }}"/>

{% endblock %}

<!-- BUTTON -->
{% block b1 %} 
<a class="btn-3d yellow" href="{{url_for('main.index')}}">Home</a>
{% endblock %}

{% block b2 %} 
<a class="btn-3d green" href="{{url_for('map.index')}}">Map</a>
{% endblock %}

{% block b3 %}
<a class="btn-3d purple" href="{{url_for('prof.index')}}">Profile</a>
{% endblock %}


<!-- Body -->
{% block body %}
<div class="content_main">
    <a href="https://codepen.io/FelipeMarcos/details/tfhEg" class="btn-3d yellow">Buttons</a>
</div>
{% endblock %}

location_app/app/templates/base_page.html
{% extends 'base.html' %}

<!-- JS -->
{% block basejs %}
{% block js %}{% endblock %}
{% endblock %}

<!-- CSS -->
{% block basecss %}
<link href="{{ url_for('static', filename='css/base_page.css') }}" rel="stylesheet" />
{% block css %}{% endblock %}
{% endblock %}

<!-- BODY -->
{% block basebody %}
<div class="container">
    <div class="title">
        <p class="title_text shadow">Trackmaster</p>
    </div>
    <div class="btnss">
        <div class="button_profile">
            {% block b1 %}{% endblock %}
        </div>
        <div class="button_map">
            {% block b2 %}{% endblock %}
        </div>
        <div class="button_3">
            {% block b3 %}{% endblock %}
        </div>
        <div class="button_logout">
            <form action="{{url_for('main.logout')}}" method="GET">
                  <button  class="btn-3d red">Log out</button>
            </form>
        </div>
    </div>
    {% block body %}{% endblock %}
</div>
{% endblock %}

location_app/app/templates/login/create.html
{% extends 'base.html' %}

<!-- TITLE -->
{% block title %} Create Account {% endblock %}

<!-- JS -->
{% block basejs %}
{% endblock %}

<!-- CSS -->
{% block basecss %}
<link href="{{ url_for('static', filename='css/login/create.css') }}" rel="stylesheet" />
{% endblock %}

<!-- BODY -->
{% block basebody %}
<div class="container">
    <div class="container_box">
        <div class="title">
            <p class="title_text shadow">Trackmaster</p>
        </div>
        <div class="create">
            <p class="create_text">Create Account</p>
        </div>
        <div class="form">
            <form action="{{url_for('login.create_account')}}" method="POST">
                <div class="form_inside">
                    <div class="username">
                        <p class="text">ID:</p><br>
                        <input type="text" name="username">
                        {% if status == 'no_id' %}
                        <p class="error_text">Wrong ID</p>
                        {% elif status == 'empty_id' %}
                        <p class="error_text">Empty ID</p>
                        {% elif status == 'user_exists' %}
                        <p class="error_text">User exists</p>
                        {% endif %}
                    </div>
                    <div class="realname">
                        <p class="text">Name:</p><br>
                        <input type="text" name="realname">
                        {% if status == 'empty_name' %}
                        <p class="error_text">Empty Name</p>
                        {% endif %}
                    </div>
                    <div class="dob">
                        <p class="text">Birthday:</p><br>
                        <div>
                            <select name="day" id="day">
                                <option value="0" selected>Day</option>
                                {% for day in time[0] %}
                                <option value="{{day}}">{{day}}</option>
                                {% endfor %}
                            </select>
                            <select name="month" id="month">
                                <option value="0" selected>Month</option>
                                {% for month in time[1] %}
                                <option value="{{month.1}}">{{month.0}}</option>
                                {% endfor %}
                            </select>
                            <select name="year" id="year">
                                <option value="0" selected>Year</option>
                                {% for year in time[2] %}
                                <option value="{{year}}">{{year}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        {% if status == 'wrong_date' %}
                        <p class="error_text">Wrong Date</p>
                        {% elif status == 'empty_bday' %}
                        <p class="error_text">Empty Date</p>
                        {% endif %}
                    </div>
                    <div class="colorr">
                        <p class="text">Favourite Color:</p><br>
                        <input type="color" name="color">
                    </div>
                    <div class="weight">
                        <p class="text">Weight (kg):</p><br>
                        <input type="text" name="weight">
                        {% if status == 'empty_weight' %}
                        <p class="error_text">Empty Weight</p>
                        {% endif %}
                    </div>
                    <div class="password">
                        <p class="text">Password:</p><br>
                        <input type="password" name="password">
                        {% if status == 'empty_pass' %}
                        <p class="error_text">Empty Password</p>
                        {% elif status == 'no_low' %}
                        <p class="error_text">Password should contain atleast 1 lowercase letter</p>
                        {% elif status == 'no_up' %}
                        <p class="error_text">Password should contain atleast 1 uppercase letter</p>
                        {% elif status == 'no_num' %}
                        <p class="error_text">Password should contain atleast 1 number</p>
                        {% elif status == 'no_sym' %}
                        <p class="error_text">Password should contain atleast 1 symbol</p>
                        {% elif status == 'weak' %}
                        <p class="error_text">Our experts recommend using a stronger password</p>
                        {% elif status == 'too_short' %}
                        <p class="error_text">Password is too short</p>
                        {% elif status == 'too_long' %}
                        <p class="error_text">Password is too long</p>
                        {% endif %}
                    </div>
                    <div class="r_password">
                        <input type="password" name="r_password">
                        {% if status == 'empty_rpass' %}
                        <p class="error_text">Empty Repeat Password</p>
                        {% elif status == 'pass_no_match' %}
                        <p class="error_text">Passwords don't match</p>
                        {% endif %}
                    </div>
                    <div class="create_button_area">
                        <button class="btn-3d blue" type="submit">Create Account</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

location_app/app/templates/login/index.html
{% extends 'base.html' %}

<!-- TITLE -->
{% block title %} Login {% endblock %}

<!-- JS -->
{% block basejs %}
{% endblock %}

<!-- CSS -->
{% block basecss %}
<link href="{{ url_for('static', filename='css/login/index.css') }}" rel="stylesheet" />
{% endblock %}

<!-- BODY -->
{% block basebody %}
<div class="container">
    <div class="container_box">
        <div class="title">
            <p class="title_text shadow">Trackmaster</p>
        </div>
        <div class="login">
            <p class="login_text">Login</p>
        </div>
        <div class="form">
            <form action="{{url_for('login.index')}}" method="POST">
                <div class="form_inside">
                    <div class="username">
                        <p class="username_text">ID:</p><br>
                        <input type="text" name="username">
                        {% if status == 'no_id' %}
                        <p class="error_text">Wrong ID</p>
                        {% elif status == 'empty_id' %}
                        <p class="error_text">Empty ID</p>
                        {% endif %}
                    </div>
                    <div class="password">
                        <p class="password_text">Password:</p><br>
                        <input type="password" name="password">
                        {% if status == 'wrong_pass' %}
                        <p class="error_text">Wrong password</p>
                        {% elif status == 'empty_pass' %}
                        <p class="error_text">Empty password</p>
                        {% endif %}
                    </div>
                    <div class="btns">
                        <div class="login_button_area">
                            <button class="btn-3d blue">Login</button>
                        </div>
                        <div class="fpass_area">
                            <a class="btn-3d yellow" href="{{url_for('login.forgot_password')}}">Forgot password?</a>
                        </div>
                    </div>  
                    <div class="cacc_area">
                        <a class="btn-3d green" href="{{url_for('login.create_account')}}">Create account</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

location_app/app/templates/login_create.html
{% extends 'base.html' %}

<!-- TITLE -->
{% block title %} Create Account {% endblock %}

<!-- JS -->
{% block basejs %}
{% endblock %}

<!-- CSS -->
{% block basecss %}
<link href="{{ url_for('static', filename='css/login_create.css') }}" rel="stylesheet" />
{% endblock %}

<!-- BODY -->
{% block basebody %}
<div class="container">
    <div class="container_box">
        <div class="title">
            <p class="title_text shadow">Trackmaster</p>
        </div>
        <div class="create">
            <p class="create_text">Create Account</p>
        </div>
        <div class="form">
            <form action="{{url_for('login.create_account')}}" method="POST">
                <div class="form_inside">
                    <div class="username">
                        <p class="username_text">ID:</p><br>
                        <input type="text" name="username">
                    </div>
                    <div class="realname">
                        <p class="realname_text">Name:</p><br>
                        <input type="text" name="realname">
                    </div>
                    <div class="dob">
                        <p class="dob_text">DOB (yyyy-mm-dd):</p><br>
                        <input type="date" name="dob" min="1920-01-01" max="{{today}}">
                    </div>
                    <div class="gender">
                        <p class="gender_text">Gender:</p><br>
                        <div class="male">
                            <input type="radio" id="male" name="gender" value="male">
                            <p>Male</p>
                        </div>
                        <div class="female">
                            <input type="radio" id="female" name="gender" value="female">
                            <p>Female</p>
                        </div>
                    </div>
                    <div class="height">
                        <p class="height_text">Height (cm):</p><br>
                        <input class="short" type="text" name="height">
                    </div>
                    <div class="weight">
                        <p class="weight_text">Weight (kg):</p><br>
                        <input class="short" type="text" name="weight">
                    </div>
                    <div class="password">
                        <p class="password_text">Password:</p><br>
                        <input type="password" name="password">
                    </div>
                    <div class="r_password">
                        <input type="password" name="r_password">
                    </div>
                    <div class="create_button_area">
                        <button class="create_button" type="submit">Create Account</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

location_app/app/templates/login_forgot.html
{% extends 'base.html' %}

<!-- TITLE -->
{% block title %} Forgot Password {% endblock %}

<!-- JS -->
{% block basejs %}
{% endblock %}

<!-- CSS -->
{% block basecss %}
<link href="{{ url_for('static', filename='css/login_forgot.css') }}" rel="stylesheet" />
{% endblock %}

<!-- BODY -->
{% block basebody %}
<div class="container">
    <div class="container_box">
        <div class="title">
            <p class="title_text shadow">Trackmaster</p>
        </div>
        <div class="forgot">
            <p class="forgot_text">Forgot Password</p>
        </div>
        <div class="form">
            <form action="{{url_for('login.forgot_password')}}" method="POST">
                <div class="form_inside">
                    <div class="username">
                        <p class="username_text">ID:</p><br>
                        <input type="text" name="username">
                    </div>
                    <div class="password">
                        <p class="password_text">New Password:</p><br>
                        <input type="password" name="password">
                    </div>
                    <div class="r_password">
                        <input type="password" name="r_password">
                    </div>
                    <div class="forgot_button_area">
                        <button class="forgot_button" type="submit">Reset Password</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

location_app/app/templates/login_index.html
{% extends 'base.html' %}

<!-- TITLE -->
{% block title %} Login {% endblock %}

<!-- JS -->
{% block basejs %}
{% endblock %}

<!-- CSS -->
{% block basecss %}
<link href="{{ url_for('static', filename='css/login_index.css') }}" rel="stylesheet" />
{% endblock %}

<!-- BODY -->
{% block basebody %}
<div class="container">
    <div class="container_box">
        <div class="title">
            <p class="title_text shadow">Trackmaster</p>
        </div>
        <div class="login">
            <p class="login_text">Login</p>
        </div>
        <div class="form">
            <form action="{{url_for('login.index')}}" method="POST">
                <div class="form_inside">
                    <div class="username">
                        <p class="username_text">ID:</p><br>
                        <input type="text" name="username">
                    </div>
                    <div class="password">
                        <p class="password_text">Password:</p><br>
                        <input type="password" name="password">
                    </div>
                    <div class="login_button_area">
                        <button class="login_button" type="submit">Login</button>
                    </div>
                    <div class="fpass_area">
                        <a href="{{url_for('login.forgot_password')}}">Forgot password?</a>
                    </div>
                    <div class="cacc_area">
                        <a href="{{url_for('login.create_account')}}">Create Account</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

location_app/app/templates/main/index.html
{% extends 'base_page.html' %}

<!-- TITLE -->
{% block title %} Main {% endblock %} 

<!-- JS -->
{% block js %}
{% endblock %}

<!-- CSS -->
{% block css %}
<link href="{{ url_for('static', filename='css/main/index.css') }}" rel="stylesheet" />
{% endblock %}

<!-- BUTTON -->
{% block b1 %} 
<a class="btn-3d yellow" href="{{url_for('prof.index')}}">Profile</a>
{% endblock %}

{% block b2 %} 
<a class="btn-3d green" href="{{url_for('map.index')}}">Map</a>
{% endblock %}

{% block b3 %}
<a class="btn-3d purple" href="{{url_for('average.index')}}">Average</a>
{% endblock %}

<!-- Body -->
{% block body %}
<div class="content_main">
    {% if advanced %}
    <a class="table_title shadow" href="{{url_for('main.advanced')}}" title="Click for less details">Your Locations</a>
    <table class="table_main">
        <tr class="shadow">
            <th>ID</th>
            <th>Longitude</th>
            <th>Latitude</th>
            <th>City</th>
            <th>Road</th>
            <th>Date</th>
            <th>Time</th>
        </tr>
        {% for item in locations %}
        <tr class="advanced">
            <td>{{ item[0] }}</td>
            <td>{{ item[1] }}</td>
            <td>{{ item[2] }}</td>
            <td>{{ item[3] }}</td>
            <td>{{ item[4] }}</td>
            <td>{{ item[5] }}</td>
            <td>{{ item[6] }}</td>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <a class="table_title shadow" href="{{url_for('main.advanced')}}" title="Click for more details">Your Locations</a>
    <table class="table_main">
        <tr class="shadow">
            <th>ID</th>
            <th>City</th>
            <th>Road</th>
            <th>Date</th>
            <th>Time</th>
        </tr>
        {% for item in locations %}
        <tr class="basic">
            <td>{{ item[0] }}</td>
            <td>{{ item[3] }}</td>
            <td>{{ item[4] }}</td>
            <td>{{ item[5] }}</td>
            <td>{{ item[6] }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
{% endblock %}

location_app/app/templates/map/index.html
{% extends 'base_page.html' %}

{% block title %} Map {% endblock %} 

<!-- JS -->
{% block js %}

<script type="text/javascript" src="https://openlayers.org/en/v4.6.5/build/ol.js"></script>

<script type="text/javascript" src="{{ url_for('static', filename='js/map/index.js') }}"></script> 
<script type="text/javascript" src="{{ url_for('static', filename='js/math.js') }}"></script> 

{% endblock %}

<!-- CSS -->
{% block css %}

<link rel="stylesheet" type="text/css" href="https://openlayers.org/en/v4.6.5/css/ol.css"/>

<link rel="stylesheet" href="{{ url_for('static', filename='css/map/index.css') }}"/>

{% endblock %}

<!-- Buttons -->
{% block b1 %} 
<a class="btn-3d yellow" href="{{url_for('main.index')}}">Home</a>
{% endblock %}

{% block b2 %} 
<a class="btn-3d green" href="{{url_for('prof.index')}}">Profile</a>
{% endblock %}

{% block b3 %}
<a class="btn-3d purple" href="{{url_for('average.index')}}">Average</a>
{% endblock %}


<!-- Body -->
{% block body %}
<div class="content_main">
    <div class="dates">
        <div class="selection">
            <select name="date" id="date">
                <option value="all" selected>All</option>
                {% for date in dates %}
                    <option value="{{date}}">{{date}}</option>
                {% endfor %}
            </select>
        </div>
        <div class="bm_1">
            <button class="btn-3d blue" onclick="get_map_for_selection()">Go</button>
        </div>
    </div>
    <div class="map" id="map">
        <script>
            initialize_map({{ locations | tojson }}, {{ weight }}, '{{ color }}');
        </script>
    </div>
    
</div>
{% endblock %}

location_app/app/templates/profile/index.html
{% extends 'base_page.html' %} 

{% block title %} Profile {% endblock %}

<!-- JS -->
{% block js %} 

<script type="text/javascript" src="{{ url_for('static', filename='js/profile/index.js') }}"></script> 
<script type="text/javascript" src="{{ url_for('static', filename='js/math.js') }}"></script> 

{% endblock %}

<!-- CSS -->
{% block css %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/profile/index.css') }}" />

{% endblock %}

<!-- Buttons -->
{% block b1 %} 
<a class="btn-3d yellow" href="{{url_for('main.index')}}">Home</a>
{% endblock %}

{% block b2 %} 
<a class="btn-3d green" href="{{url_for('map.index')}}">Map</a>
{% endblock %}

{% block b3 %}
<a class="btn-3d purple" href="{{url_for('average.index')}}">Average</a>
{% endblock %}


<!-- Body -->
{% block body %}
<div class="content_main">
    <script>
        setup({{ locations | tojson }}, {{user[0][4]}}, {{ dates | tojson }});
    </script>
    <div class="p_title">
        <p class="shadow">My profile</p>
    </div>
    <div class="p_pic" id="pic">
        <img src="{{ url_for('static', filename='img/picture/first.jpg') }}" alt="profile">
    </div>
    <div class="ID">
        <p class="label">ID:</p>
    </div>
    <div class="ID1">
        <p class="info">{{user[0][0]}}</p>
    </div>
    <div class="name">
        <p class="label">Name:</p>
    </div>
    <div class="name1">
        <p class="info">{{user[0][1]}}</p>
    </div>
    <div class="date">
        <p class="label">Birthday:</p>
    </div>
    <div class="date1">
        <p class="info">{{user[0][2]}}</p>
    </div>
    <div class="color">
        <p class="label">Favourite color:</p>
    </div>
    <div class="weight">
        <p class="label">Weight:</p>
    </div>
    <div class="updates">
        <form action="" method="POST">
            <div class="weight1">
                <input class="info" type="text" name="weight" value='{{user[0][4]}}'>
            </div>
            <div class="color1">
                <input type="color" name="color" value='{{user[0][3]}}'>
            </div>
            <div class="submit">
                <button class="btn-3d green">Update</button>
            </div>
        </form>
    </div>
    <div class="city">
        <p class="label">Favourite city:</p>
    </div>
    <div class="city1">
        <p class="info">{{user[1][0][0]}}</p>
    </div>
    <div class="street">
        <p class="label">Favourite Street:</p>
    </div>
    <div class="street1">
        <p class="info">{{user[1][1][0]}}</p>
    </div>
    <div class="cal">
        <p class="label">Total calories burnt:</p>
    </div>
    <div class="cal1">
        <p class="info" id="cal">???</p>
    </div>
    <div class="tcal">
        <p class="label">Top calories:</p>
    </div>
    <div class="tcal1">
        <p class="info" id="tcal">???</p>
    </div>
    <div class="speed">
        <p class="label">Top speed:</p>
    </div>
    <div class="speed1">
        <p class="info" id="speed">???</p>
    </div>
    <div class="type">
        <p class="label">Your type:</p>
    </div>
    <div class="type1">
        <p class="info" id="type">???</p>
    </div>
    <div class="dist">
        <p class="label">Total distance:</p>
    </div>
    <div class="dist1">
        <p class="info" id="dist">???</p>
    </div>
    <div class="tdist">
        <p class="label">Top distance:</p>
    </div>
    <div class="tdist1">
        <p class="info" id="tdist">???</p>
    </div>
</div>
{% endblock %}